name: "Java CI with Gradle"

on:
  push:

permissions:
  contents: "read"

jobs:
  build:
    runs-on: "ubuntu-latest"

    steps:
      - uses: "actions/checkout@v3"
      - uses: "actions/setup-java@v3"
        with:
          distribution: "temurin"
          java-version: "17"

      - run: "docker compose up --detach"

      - run: "./gradlew build"
